services:
  bmsserver:
    build:
      context: .
      dockerfile: Dockerfile
    image: bmsserver:latest
    environment:
      - STEAM_USER=${STEAM_USER:-}
      - STEAM_PASS=${STEAM_PASS:-}
      - INSTALL_ON_START=${INSTALL_ON_START:-false}
    volumes:
      - bms-data:/home/bms/wine64
      - ./installers:/home/bms/installers:ro
    ports:
      - "5900:5900" # x11vnc VNC port
      - "2934:2934/udp" # BMS MP 
      - "2935:2935/udp" # BMS MP 
      - "9987:9987/udp" # BMS IVC
      - "9988:9988/udp" # BMS IVC
      - "9989:9989/udp" # BMS IVC
    tty: true
    stdin_open: true
    restart: unless-stopped

volumes:
  bms-data: