version: '3.8'

services:
  bmsserver:
    build:
      context: .
      dockerfile: Dockerfile
    image: bmsserver:latest
    environment:
      INSTALL_ON_START: "false"   # Set to "true" to force install on startup
      # Uncomment and fill for Steam install:
      # STEAM_USER: "your_steam_username"
      # STEAM_PASS: "your_steam_password"
    volumes:
      - ./bmsdata:/home/bms/wine64
      - ./installers:/home/bms/installers:ro
    ports:
      - "2934:2934/udp"
      - "2935:2935/udp"
      - "9987:9987/udp"
      - "9988:9988/udp"
      - "9989:9989/udp"
    restart: unless-stopped
